tasks:
  - init: |
      sudo docker pull registry.jetbrains.team/p/prj/containers/projector-webstorm
    command: |
      sudo mkdir -p .jetbrains; sudo touch .jetbrains/.gitkeep; sudo chown -R 1000:1000 .jetbrains
      sudo docker run --rm -p 8887:8887 -v /workspace/template-jetbrains-webstorm/.jetbrains/home/projector-user -it registry.jetbrains.team/p/prj/containers/projector-webstorm

ports:
  - port: 8887
    visibility: private
    onOpen: open-browser
